"""empty message

Revision ID: 654e18404a83
Revises: 
Create Date: 2021-02-19 08:28:00.686479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654e18404a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('open_hour', sa.Time(), nullable=False),
    sa.Column('close_hour', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.Enum('gluten', 'peanuts', 'tree_nuts', 'celery', 'mustard', 'eggs', 'milk', 'sesame', 'fish', 'custaceans', 'molluscs', 'soya', 'sulphites', 'lupin', 'vegetarian_friendly', 'vegan_friendly', name='enum_info'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_contains_meal_info',
    sa.Column('meal', sa.Integer(), nullable=True),
    sa.Column('meal_info', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['meal_info'], ['meal_info.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_contains_meal_info')
    op.drop_table('meal')
    op.drop_table('menu')
    op.drop_table('template')
    op.drop_table('meal_info')
    op.drop_table('category')
    op.drop_table('business')
    # ### end Alembic commands ###
